/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roots */
        get: operations["get_roots_api_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/{root}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Serve raw file bytes from any root, for preview in the frontend.
         */
        get: operations["get_file_api_file__root___path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Datasets */
        get: operations["get_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Info */
        get: operations["get_info_api_d__root___path__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_d__root___path__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rows */
        get: operations["get_rows_api_d__root___path__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/row/{offset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Row */
        get: operations["get_row_api_d__root___path__row__offset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/blob/{offset}/{column}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blob
         * @description Stream one cell's raw bytes with a detected Content-Type.
         *
         *     Covers v1 / v2 Lance blob columns and plain binary columns. Content-Type
         *     is taken from the blob's source URI suffix when available (v2 URI-refs),
         *     and falls back to magic-byte sniffing of the first bytes. Non-binary
         *     columns 404.
         */
        get: operations["get_blob_api_d__root___path__blob__offset___column__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get View */
        get: operations["get_view_api_d__root___path__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{root}/{path}/view/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get View Detail */
        get: operations["get_view_detail_api_d__root___path__view__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunDetail */
        AgentRunDetail: {
            /** Row */
            row: {
                [key: string]: unknown;
            };
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** AgentRunSidebar */
        AgentRunSidebar: {
            /** Row Offset */
            row_offset: number;
            /** Session Id */
            session_id?: string | null;
            /** Correct */
            correct?: boolean | null;
            /** Error */
            error?: string | null;
            /** Output */
            output?: unknown | null;
            /** Metadata */
            metadata?: unknown | null;
        };
        /** AgentRunStats */
        AgentRunStats: {
            /** Total */
            total: number;
            /** Ok */
            ok: number;
            /** Wrong */
            wrong: number;
            /** Error */
            error: number;
            /** Pending */
            pending: number;
            /** Accuracy */
            accuracy?: number | null;
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Nullable */
            nullable: boolean;
            /**
             * Is Blob
             * @default false
             */
            is_blob: boolean;
        };
        /** DatasetEntry */
        DatasetEntry: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Kind */
            kind: string;
            /** Row Count */
            row_count?: number | null;
            /** Size */
            size?: number | null;
        };
        /** DatasetInfoResponse */
        DatasetInfoResponse: {
            /** Row Count */
            row_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
            /** Plugin */
            plugin?: string | null;
            /**
             * Filters
             * @default []
             */
            filters: string[];
        };
        /** DatasetListResponse */
        DatasetListResponse: {
            /** Root */
            root: string;
            /** Path */
            path: string;
            /** Datasets */
            datasets: components["schemas"]["DatasetEntry"][];
        };
        /** GenericRowListResponse */
        GenericRowListResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PluginDetailResponse */
        PluginDetailResponse: {
            /** Plugin */
            plugin: string;
            data: components["schemas"]["AgentRunDetail"];
        };
        /** PluginViewResponse */
        PluginViewResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Rows */
            rows: components["schemas"]["AgentRunSidebar"][];
            stats?: components["schemas"]["AgentRunStats"] | null;
            /** Plugin */
            plugin: string;
        };
        /** RootInfo */
        RootInfo: {
            /** Name */
            name: string;
            /** Uri */
            uri: string;
        };
        /** RootsResponse */
        RootsResponse: {
            /** Roots */
            roots: components["schemas"]["RootInfo"][];
            /** Default */
            default: string;
        };
        /** SchemaResponse */
        SchemaResponse: {
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_roots_api_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootsResponse"];
                };
            };
        };
    };
    get_file_api_file__root___path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_datasets_api_datasets_get: {
        parameters: {
            query: {
                root: string;
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_info_api_d__root___path__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_d__root___path__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rows_api_d__root___path__rows_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                root: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericRowListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_row_api_d__root___path__row__offset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
                path: string;
                offset: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blob_api_d__root___path__blob__offset___column__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
                path: string;
                offset: number;
                column: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_api_d__root___path__view_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                filter?: string;
            };
            header?: never;
            path: {
                root: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_detail_api_d__root___path__view__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
                path: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
