/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Datasets */
        get: operations["get_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{db_path}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_d__db_path__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{db_path}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rows */
        get: operations["get_rows_api_d__db_path__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/d/{db_path}/runs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_d__db_path__runs__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ColumnInfo */
        ColumnInfo: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Nullable */
            nullable: boolean;
        };
        /** DatasetEntry */
        DatasetEntry: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Kind */
            kind: string;
            /** Row Count */
            row_count?: number | null;
        };
        /** DatasetListResponse */
        DatasetListResponse: {
            /** Prefix */
            prefix: string;
            /** Datasets */
            datasets: components["schemas"]["DatasetEntry"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RowListResponse */
        RowListResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Rows */
            rows: components["schemas"]["RowSummary"][];
            stats: components["schemas"]["Stats"];
        };
        /** RowSummary */
        RowSummary: {
            /** Row Offset */
            row_offset: number;
            /** Session Id */
            session_id?: string | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Correct */
            correct?: boolean | null;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            row: components["schemas"]["RowSummary"];
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** SchemaResponse */
        SchemaResponse: {
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
        };
        /** Stats */
        Stats: {
            /** Total */
            total: number;
            /** Ok */
            ok: number;
            /** Wrong */
            wrong: number;
            /** Error */
            error: number;
            /** Pending */
            pending: number;
            /** Accuracy */
            accuracy?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_datasets_api_datasets_get: {
        parameters: {
            query?: {
                prefix?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_d__db_path__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rows_api_d__db_path__rows_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                status?: string;
            };
            header?: never;
            path: {
                db_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_d__db_path__runs__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db_path: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
